server:
  port: 8090

spring:
  application:
    name: spring-gateway
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
      routes:
        - id: cliente
          uri: http://localhost:8081/
          predicates:
            - Path=/clientes/**
          #filters:
          #  - SetPath=/clientes/
        - id: angular
          uri: http://localhost:4200/
          predicates:
            - Path=/**
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: spring
            client-id: client
            client-secret: secret
            scope: openid, profile, read
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:8090/login/oauth2/code/{registrationId}
        provider:
          spring:
            issuer-uri: http://localhost:9000

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

